function print_help()
  printf("\n")
  printf("\t\tTrabalho-2 Calculo numerico\n")
  printf("\n")
  printf("Lista de argumentos obrigatórios:\n")
  printf("\t-f1 \t\t- arquivo com matriz\n")
  printf("\t-f2 \t\t- arquivo com vetor\n")
  printf("\t-f3 \t\t- arquivo com matriz\n")
  printf("\t-f4 \t\t- arquivo com vetor\n")
  printf("\t-e  \t\t- erro permitido. default: 10^-5\n")
  printf("\n")
  printf("Exemplos:\n")
  printf("\nEx1: octave trabalho.m -f1 matriz1 -f2 vetor1 -f3 matriz2 -f4 vetor2 -e '10^-3'\n")
endfunction
